apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: shippingservice
spec:
  hosts:
  - shippingservice
  http:
  - match:
    - sourceLabels:
        app: "frontend"
    fault:
      delay:
        fixedDelay: 0.2s
        percent: 100
    route:
    - destination:
        host: shippingservice
  - match:
    - sourceLabels:
        app: "checkoutservice"
      uri:
        regex: ".*/GetQuote"
    fault:
      delay:
        fixedDelay: 0.4s
        percent: 100
    route:
    - destination:
        host: shippingservice
  - route:
    - destination:
        host: shippingservice